## Exercise 1:  
Create a numpy array containing the numbers from 1 to 10, and then reshape it to a 2x5 matrix.


In [18]:
# creating numpy array

import numpy as np

arr = np.arange(1,11)
print(arr)


[ 1  2  3  4  5  6  7  8  9 10]


In [22]:
# reshaping to 2x5 matrix

reshaped_arr = arr.reshape(2,5)
print('Reshaped array:\n',reshaped_arr)

Reshaped array:
 [[ 1  2  3  4  5]
 [ 6  7  8  9 10]]


## Exercise 2: 
Create a numpy array containing the numbers from 1 to 20, and then extract the elements between the 5th and 15th index.


In [50]:
# creating numpy array

arr = np.arange(1,21)
print(arr)

[ 1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19 20]


In [34]:
# extract the element b/w 5th & 15th index

new_arr = arr[5:16]
print(new_arr)

[ 6  7  8  9 10 11 12 13 14 15 16]


## Exercise 3: 
Create a Pandas series with the following data: {'apples': 3, 'bananas': 2, 'oranges': 1}. Then, add a new item to the series with the key 'pears' and the value 4.


In [72]:
# creating pandas series

import pandas as pd

ser = pd.Series({'apples': 3, 'bananas': 2, 'oranges': 1})
ser

apples     3
bananas    2
oranges    1
dtype: int64

In [74]:
# adding new item to the series

ser['pears'] = 4
ser

apples     3
bananas    2
oranges    1
pears      4
dtype: int64

## Exercise 4: 
Create a dataframe with the following columns: name, age, and gender. The dataframe should have 10 rows of data.


In [78]:
# creating dataframe

data = {
    'Name': ['Alice', 'Bob', 'Charlie', 'David', 'Eve', 'Frank', 'Grace', 'Hannah', 'Ian', 'Jack'],
    'Age': [25, 30, 22, 28, 24, 27, 32, 26, 23, 31],
    'Gender': ['Female', 'Male', 'Male', 'Male', 'Female', 'Male', 'Female', 'Female', 'Male', 'Male']
}
df = pd.DataFrame(data)
df

Name  Age  Gender
0    Alice   25  Female
1      Bob   30    Male
2  Charlie   22    Male
3    David   28    Male
4      Eve   24  Female
5    Frank   27    Male
6    Grace   32  Female
7   Hannah   26  Female
8      Ian   23    Male
9     Jack   31    Male

## Exercise 5: 
Add a new column to the data frame created in question 1, called occupation. The values for this column should be Programmer, Manager, and Analyst, corresponding to the rows in the dataframe.


In [81]:
# adding the new column 'occupation'

occupation = ['Programmer', 'Manager', 'Analyst', 'Programmer', 'Manager','Analyst', 'Programmer', 'Manager', 'Analyst', 'Programmer']

df['Occupation'] = occupation
df

Name  Age  Gender  Occupation
0    Alice   25  Female  Programmer
1      Bob   30    Male     Manager
2  Charlie   22    Male     Analyst
3    David   28    Male  Programmer
4      Eve   24  Female     Manager
5    Frank   27    Male     Analyst
6    Grace   32  Female  Programmer
7   Hannah   26  Female     Manager
8      Ian   23    Male     Analyst
9     Jack   31    Male  Programmer

## Exercise 6: 
Select the rows of the dataframe where the age is greater than or equal to 30.


In [84]:
df[df['Age'] >= 30]

Name  Age  Gender  Occupation
1    Bob   30    Male     Manager
6  Grace   32  Female  Programmer
9   Jack   31    Male  Programmer

## Exercise 7: 
Convert this dataframe to a csv file and read that csv file, finally display the contents.


In [102]:
# converting dataframe to csv file

df.to_csv('data.csv', index = False)

In [108]:
# read the csv file

csv_file = pd.read_csv('data.csv')
csv_file

Name  Age  Gender  Occupation
0    Alice   25  Female  Programmer
1      Bob   30    Male     Manager
2  Charlie   22    Male     Analyst
3    David   28    Male  Programmer
4      Eve   24  Female     Manager
5    Frank   27    Male     Analyst
6    Grace   32  Female  Programmer
7   Hannah   26  Female     Manager
8      Ian   23    Male     Analyst
9     Jack   31    Male  Programmer